server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.142.111
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.142.111
    port: 6379  # 可以不写 默认就是6379

ly:
  sms:
    accessKeyId: LTAI4FcmnYyc1rBsn5LExrhx    #https://usercenter.console.aliyun.com/?spm=5176.12207334.0.0.57bd1cbeCyEAkk#/manage/ak
    accessKeySecret: xteDuOeb7haXvep4AKeNnej1w2wHet
    signName: 乐优商城  #签名模板  https://dysms.console.aliyun.com/dysms.htm?spm=5176.12818093.products-grouped.ddysms.44f116d0Xmpmmn#/domestic/text/sign
    verifyCodeTemplate: SMS_183247204  #https://dysms.console.aliyun.com/dysms.htm?spm=5176.12818093.products-grouped.ddysms.44f116d0Xmpmmn#/domestic/text/template