server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver  可以不写
    url: jdbc:mysql://192.168.1.103:3306/leyou?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    #data-password: 123456   一定不要粗心写成这个鬼东西
    password: 123456
  rabbitmq:
    host: 192.168.142.111
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.142.111
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.103:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.103
mybatis:
  type-aliases-package: com.leyou.pojo  #指定扫描类型
ly:
  sms:
    exchange: ly.sms.exchange
    routingKey: sms.verify.code
    timeout: 5 #过期时间  min